### PR TITLE
Fix `go test -count n`

### PR DESCRIPTION
**Pull request by eNV25**
Calls client.Clear the client's playlist on teardown, for the next iteration to have
a clean state.

```
$ go test -count 2 ./...
--- FAIL: TestPlaylistInfo (0.00s)
    client_test.go:98: Client.PlaylistInfo(-1, -1) len = 5 need 4
FAIL
FAIL	github.com/fhs/gompd/v2/mpd	0.039s
?   	github.com/fhs/gompd/v2/mpd/internal/server	[no test files]
FAIL
```

### CODE REVIEW

**Comment by eNV25** [comment]
Looks like the unsuccessful test is due to an unrelated random reason.

It just needs to be re-run.

**Comment by fhs** [comment]
Can we add `go test -count 2` in Github CI? The tests are fast, so it seems worth it.

**Comment by eNV25** [comment]
@fhs

**Review by fhs — APPROVED** [review]
lgtm

**Pull request merged**
